# HKU QIDS 2023 Quantitative Investment Competition: Model

## Init Config

In [114]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from qids_package.qids import *
import warnings
from submit import submit

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

warnings.filterwarnings("ignore")

In [2]:
seed = 257248
stock_num = 54
day_num_total = 1000
day_num = 1000 - 2
test_day_num = 700
timeslot_num = 50

In [3]:
def std(train, valid, test=None):
    scaler = StandardScaler()
    scaler.fit(train)
    train = scaler.transform(train)
    valid = scaler.transform(valid)
    if test is not None:
        test = scaler.transform(test)
    return train, valid, test

In [4]:
def calc_corr(df1, df2):
    return np.corrcoef(df1, df2)[0][1]

In [72]:
# def evaluate(model, train, valid, test, train_y, valid_y, return_pred=True, version=2, return_auc=False, plot_auc=False):
#     model.fit(train, train_y)
#     if version == 2:
#         model_train_y = model.predict(train)
#         model_valid_y = model.predict(valid)
#         pred = model.predict(test)
#         acr_train = model.score(train, train_y)
#         acr_valid = model.score(valid, valid_y)
#         print(calc_corr(train_y, model_train_y))
#         print(calc_corr(valid_y, model_valid_y))
#         if return_pred:
#             return pred
    #     cm = confusion_matrix(train_y, model_train_y)
    #     tn, fp, fn, tp = cm.ravel()
    #     print(f"Train AUROC: {roc_auc_score(train_y, model_train_y):.4f}; FP: {fp:>4d}; FN: {fn:>4d}")
    #     cm = confusion_matrix(valid_y, model_valid_y)
    #     tn, fp, fn, tp = cm.ravel()
    #     print(f"Valid AUROC: {roc_auc_score(valid_y, model_valid_y):.4f}; FP: {fp:>4d}; FN: {fn:>4d}")
    #     print()
    # elif version == 3:
    #     pred_train = model.predict(train)
    #     pred_valid = model.predict(valid)
    #     pred = model.predict(test)
    #     print(f"Train RMSE: {mse(train_y, pred_train, squared=False):.4f}")
    #     print(f"Valid RMSE: {mse(valid_y, pred_valid, squared=False):.4f}")
    # else:
    #     model_train_y = model.predict_proba(train)[:,1]
    #     model_valid_y = model.predict_proba(valid)[:,1]
    #     pred = model.predict_proba(test)[:,1]
    #     acr_train = model.score(train, train_y)
    #     acr_valid = model.score(valid, valid_y)
    #     print(f"Train Accuracy: {acr_train:.4f}; Validation Accuracy: {acr_valid:.4f}")
    #     auc_train = roc_auc_score(train_y, model_train_y)
    #     auc_valid = roc_auc_score(valid_y, model_valid_y)
    #     print(f"Train AUROC: {auc_train:.4f}")
    #     print(f"Valid AUROC: {auc_valid:.4f}")
    #     print()
    # if plot_auc:
    #     try:
    #         fpr1, tpr1, thresholds1 = roc_curve(train_y, model_train_y)
    #         fpr2, tpr2, thresholds2 = roc_curve(valid_y, model_valid_y)
    #         plt.plot([0,1], 'k--')
    #         plt.plot(fpr1, tpr1, label= "Train")
    #         plt.plot(fpr2, tpr2, label= "Valid")
    #         plt.legend()
    #         plt.xlabel("FPR")
    #         plt.ylabel("TPR")
    #         plt.title('AUROC Curve')
    #         plt.show()
    #     except:
    #         pass
    # if return_pred and return_auc and version == 1:
    #     return pred, auc_train, auc_valid
    # elif return_pred:
    #     return pred
    # else:
    #     return

In [152]:
def evaluate(model, train, test, train_y, real_y):
    model.fit(train, train_y)
    model_train_y = model.predict(train)
    pred = model.predict(test)
    # return pred
    # pred = np.array(model.predict(test)).reshape(-1,1)
    # pred = pred[:37692]
    # real_y = np.array(real_y).reshape(-1,1)
    # print(calc_corr(train_y, model_train_y))
    # print(calc_corr(real_y, pred))
    # print(real_y.shape)
    # print(pred.shape)
    # print("train_score",calc_corr(train_y, model_train_y))
    # print("prediction_score",calc_corr(pred, real_y))
    # train_y = pd.DataFrame(train_y)
    # model_train_y = pd.DataFrame(model_train_y)
    # combined0 = pd.concat([train_y,model_train_y],axis = 1)
    # print(combined0.corr())
    # pred_temp = pd.DataFrame(pred_temp)
    # real_y = pd.DataFrame(real_y)
    # combined = pd.concat([pred_temp,real_y],axis = 1)
    # print(combined.corr())
    # dt = pd.read_csv("../sub/sample_submission.csv")
    # dt["stock_id"] = dt["date_time"].apply(lambda x: x.split("d")[0][1:]).astype("int")
    # dt["day"] = dt["date_time"].apply(lambda x: x.split("d")[1][:]).astype("int")
    # dt = dt.drop(columns=["return"]).sort_values(by=["stock_id", "day"])
    # dt = dt.reset_index(drop=True)
    # pred = pd.concat([dt, pd.DataFrame(pred, columns=["return"])], axis=1)
    # pred = pred.sort_values(by=["day", "stock_id"]).reset_index(drop=True)["return"]
    print(calc_corr(train_y, model_train_y))
    print(calc_corr(real_y, pred[:37692]))
    score = calc_corr(real_y, pred[:37692])
    # pred_subset = []
    # for stock in range(stock_num):
    #     stock_info = pred[stock*test_day_num:(stock+1)*test_day_num-2]
    #     pred_subset.append(stock_info)
    # pred_subset = np.array(pred_subset).reshape(-1,1).squeeze(1)
    # print(calc_corr(np.array(real_y), pred_subset))
    return pred

In [6]:
def evaluate2(model, train, test, train_y, real_y):
    model.fit(train, train_y)
    model_train_y = model.predict(train)
    pred = model.predict(test)
    # print(calc_corr(train_y, model_train_y))
    # print(calc_corr(real_y, pred[:698]))
    return pred

## Load Data

In [169]:
write_path = "../data/"

train_path = write_path + "train.csv"
test_path = write_path + "test.csv"
# real_return_path = write_path + "real_return.csv"
real_return_path = write_path + "real_return_reorder.csv"
real_test_path = write_path + "return2.csv"

train = pd.read_csv(train_path)
test = pd.read_csv(test_path)
real_return = pd.read_csv(real_return_path)
real_test = pd.read_csv(real_test_path)

In [137]:
test

,date_time,stock_id,day,turnoverRatio,transactionAmount,pe_ttm,pe,pb,ps,pcf,...,high_mean,low_mean,volume_mean,money_mean,high_max,volume_max,money_max,low_min,price_diff,price_diff_max
0,s0d1001,0,1001,1.1718,9290.0,63.6900,63.6900,1.6398,1.5477,-40.9539,...,12.317646,12.267632,240548.82,2.953956e+06,12.4050,946319.0,1.153619e+07,12.0773,0.011992,0.017983
1,s0d1002,0,1002,1.6209,9230.0,64.8547,64.8547,1.6697,1.5760,-41.7028,...,12.624250,12.569146,332741.02,4.191007e+06,12.7570,1003636.0,1.264396e+07,12.4172,0.010699,0.015488
2,s0d1003,0,1003,1.2796,8531.0,65.0386,65.0386,1.6745,1.5804,-41.8210,...,12.619392,12.579582,262688.38,3.309048e+06,12.7206,883806.0,1.105600e+07,12.4779,0.005806,0.007699
3,s0d1004,0,1004,1.7146,10798.0,65.5903,65.5903,1.6887,1.5938,-42.1758,...,12.788354,12.735674,351987.22,4.490107e+06,12.9391,889304.0,1.120074e+07,12.5021,0.007655,0.008609
4,s0d1005,0,1005,1.6107,11239.0,66.3872,66.3872,1.7092,1.6132,-42.6882,...,12.968718,12.912648,330654.04,4.277405e+06,13.0969,1034687.0,1.346538e+07,12.6721,0.007583,0.008528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37795,s53d1696,53,1696,0.6138,11883.0,14.8783,18.1042,2.1825,0.3350,13.5864,...,16.425872,16.366644,110750.00,1.814682e+06,16.4955,344900.0,5.611515e+06,16.2042,0.006680,0.010368
37796,s53d1697,53,1697,0.8706,15871.0,14.8783,18.1042,2.1825,0.3350,13.5864,...,16.321732,16.249874,157074.00,2.556835e+06,16.4955,642700.0,1.039394e+07,16.0829,0.003760,0.018571
37797,s53d1698,53,1698,0.8237,18198.0,14.5151,17.6623,2.1292,0.3268,13.2547,...,16.131648,16.077022,148626.00,2.396161e+06,16.4470,631300.0,1.036225e+07,15.9129,0.007514,0.009018
37798,s53d1699,53,1699,0.5752,13761.0,14.3941,17.5150,2.1114,0.3241,13.1442,...,16.019488,15.960262,103776.00,1.657690e+06,16.1678,365900.0,5.828049e+06,15.8280,0.009916,0.012204
37799,s53d1700,53,1700,0.5977,11139.0,14.6032,17.7694,2.1421,0.3288,13.3351,...,16.046190,15.985752,107846.00,1.728436e+06,16.1435,323300.0,5.166492e+06,15.8401,0.008409,0.009177

In [161]:
train_y = train["return"]
train = train.drop(columns=["return", "date_time", "stock_id", "day"])
# train = train.iloc[:, [4,14,15,17,18]]
test = test.drop(columns=["date_time", "stock_id", "day"])
# test = test.iloc[:, [4,14,15,17,18]]
real_y = real_return["return"]

In [162]:
real_return

      date_time    return
0       s0d1001  0.020568
1       s0d1002  0.011545
2       s0d1003  0.021110
3       s0d1004 -0.002853
4       s0d1005  0.015037
...         ...       ...
37687  s53d1694 -0.024531
37688  s53d1695 -0.003685
37689  s53d1696 -0.024411
37690  s53d1697 -0.032546
37691  s53d1698  0.006065

[37692 rows x 2 columns]

## Normalization

In [21]:
# train, valid, test = std(train.iloc[:, 3:-1], valid.iloc[:, 3:-1], test.iloc[:, 3:])

## Model

### Linear Regression

In [166]:
model = LinearRegression()
pred = evaluate(model, train, test, train_y, real_y)

0.08234269047109077
-0.006393063831618757

### Ridge Regression

In [164]:
model = Ridge(alpha=1e8)
pred = evaluate(model, train, test, train_y, real_y)

0.06289665936118756
-0.0126673576601237

### Lasso Regression

In [165]:
model = Lasso(alpha=1)
pred = evaluate(model, train, test, train_y, real_y)

0.06256235875075056
-0.012370882653915925

In [155]:
len(pred)

37800

In [147]:
# [1e-1,1e-2,1e-3,1e-4,1e-5,1e-6,1e-7,1e-8,1e-9,1e-10]
# [1e1,1e2,1e3,1e4,1e5,1e6,1e7,1e8,1e9,1e10]
for i in [0.012]:
    result = None
    for stock in range(stock_num):
        start = stock * day_num
        end = start + day_num
        model = Ridge(alpha=i, normalize=True)
        pred = evaluate2(
            model, 
            train.iloc[stock*day_num:(stock+1)*day_num, :], 
            test.iloc[stock*test_day_num:(stock+1)*test_day_num, :], 
            train_y.iloc[stock*day_num:(stock+1)*day_num], 
            real_y.iloc[stock*test_day_num:(stock+1)*test_day_num-2]
            # real_y.iloc[[i for i in range(stock, len(real_y), stock_num)]]
        )
        if result is None:
            result = pred
        else:
            result = np.concatenate([result, pred], axis=0)
    print(i, calc_corr(result[:37692], real_y))

0.012 -0.0037978050673910333

### SGDBoosting

In [134]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
# for i in [6508,36400]:
score_lst = []
# for i in range(100):
for i in range(10):
# for i in range(1000,10000):
    # for j in [1e-4,1e-5,1e-6]:
    model = make_pipeline(StandardScaler(),SGDRegressor(max_iter=10000, tol=1e-6,penalty='l1',random_state=i))
    # model = Lasso(alpha=1)
    pred,score = evaluate(model, train, test, train_y, real_y)
    score_lst.append(score)
print(score_lst.index(min(score_lst)), min(score_lst))
print(score_lst)
    # print(i, calc_corr(result[:37692], real_y))

0.05329483833882731
0.0675238394516049
0.05475500834135985
0.062335539675324826
0.05613983193803298
0.06014389807795014
0.05619619738278732
0.06497160314388964
0.04004234203767063
0.04518591083192085
0.06152711945908008
0.06024638921383144
0.056991023825180245
0.06169022702331682
0.05899185391761314
0.06526031970726237
0.01155471301596398
0.02219098394638162
0.05490551380818942
0.06249404560259867
8 0.02219098394638162
[0.0675238394516049, 0.062335539675324826, 0.06014389807795014, 0.06497160314388964, 0.04518591083192085, 0.06024638921383144, 0.06169022702331682, 0.06526031970726237, 0.02219098394638162, 0.06249404560259867]

In [146]:
pred_df = pd.DataFrame(pred,columns=["return"])
# return_df = pd.concat([real_return,pred_df[37692:]], axis=0)
# return_df
idx_lst = []
for i in range(108):
    idx_lst.append(i)
date_lst = []
for i in range(54):
    for j in range(1699,1701):
        date_lst.append('s'+str(i)+'d'+str(j))
date_df = pd.DataFrame(np.array(date_lst),columns=["date_time"])


pred_df = pred_df[37692:].reset_index().iloc[:,1]
lower_df = pd.concat([date_df,pred_df], axis=1)
# lower_df = lower_df.rename(columns={'0':'date_time','0':'return'})
lower_df
lower_df

    date_time  return
0     s0d1699     NaN
1     s0d1700     NaN
2     s1d1699     NaN
3     s1d1700     NaN
4     s2d1699     NaN
..        ...     ...
103  s51d1700     NaN
104  s52d1699     NaN
105  s52d1700     NaN
106  s53d1699     NaN
107  s53d1700     NaN

[108 rows x 2 columns]

In [113]:
final_real = pd.concat([real_return,lower_df],axis=0).reset_index().iloc[:,[1,2]]
final_real.to_csv("return2.csv", index=False)

## Submission

In [167]:
submit(pred)

## Test

In [174]:
sub_file = pd.read_csv("../sub/submission_20230310_6.csv")
pd.concat([sub_file,real_test], axis=1).corr()

          return    return
return  1.000000  0.034581
return  0.034581  1.000000

In [171]:
real_test

      date_time    return
0       s0d1001  0.020568
1       s1d1001 -0.007209
2       s2d1001  0.017325
3       s3d1001  0.029526
4       s4d1001  0.049465
...         ...       ...
37795  s51d1700 -0.001257
37796  s52d1699 -0.002695
37797  s52d1700 -0.003714
37798  s53d1699 -0.002080
37799  s53d1700 -0.000960

[37800 rows x 2 columns]